### PR TITLE
Fix DeprecationWarning issues in Python code.

### LINKED ISSUE #44: DeprecationWarning: invalid escape sequence on regex pattern strings
When running Python 3.6.5 and using the cpe module with python -OO, it outputs the following DeprecationWarning messages:

> <virtual_env>/lib/python3.6/site-packages/cpe/comp/cpecomp1_1.py:57:` DeprecationWarning: invalid escape sequence \w
>  _STRING = "\w\.\-,\(\)@\#"
><virtual_env>/lib/python3.6/site-packages/cpe/comp/cpecomp2_2.py:52: DeprecationWarning: invalid escape sequence \d
>  _VALUE_PATTERN = "^([\d\w\._\-~%]+)$"

It looks like those lines might just need to be prefixed with 'r' in the code to indicate that they are raw strings.

### PR DESCRIPTION
**Pull request by vEpiphyte**
Closes #44

### CODE REVIEW

**Comment by vEpiphyte** [comment]
@creekorful Can you look at this and cut a release if merged? This should clean up warnings that are generated for many users.

**Comment by creekorful** [comment]
@vEpiphyte thank you for your contribution!

**Comment by vEpiphyte** [comment]
@creekorful Do you know if there are any plans to publish an updated package? In 3.12 these became SyntaxWarnings, and in a future Python release they will become SyntaxErrors.

**Comment by creekorful** [comment]
I think this will be done before end of month :)

**Comment by vEpiphyte** [comment]
Wonderful :) I and many others look forward to it :)

**Comment by agners** [comment]
@creekorful we just encountered this recently as well. So friendly ping on this one, it seems no new release made it so far. :smile:

**Pull request merged**
